name: Check Data in Another Repo
on:
  push:
    branches:
      - 'feature/*'
  workflow_dispatch:

jobs:
  check-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Clone target repo
        run: |
          git clone https://${{ secrets.MY_GIT_TOKEN }}@github.com/codeXGT/Lesson_1.git

      - name: Compare files
        run: |
          mkdir -p report
          echo "Checking files..." > report/result.txt

          # Loop through each file in src/ of triggered repo
          for srcfile in $(find src -type f); do
            filename=$(basename "$srcfile")

            # Search for file with same name inside Lesson_1/
            targetfile=$(find Lesson_1 -type f -name "$filename" | head -n 1)

            if [ -n "$targetfile" ]; then
              if cmp -s "$srcfile" "$targetfile"; then
                echo "✅ $filename is identical in both repos." >> report/result.txt
              else
                echo "❗ $filename exists but differs." >> report/result.txt
              fi
            else
              echo "❌ $filename does not exist in target repo." >> report/result.txt
            fi
          done

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: check-report
          path: report/result.txt

      - name: Summary of Check
        run: |
          echo "==== File Comparison Summary ===="
          cat report/result.txt
