name: List Files and Download CSV

on:
  workflow_dispatch:

jobs:
  list-files:
    runs-on: ubuntu-latest

    steps:
      - name: Clone target repo
        run: |
          git clone https://${{ secrets.MY_GIT_TOKEN }}@github.com/codeXGT/Lesson_1.git

      - name: Generate CSV file with file names
        run: |
          mkdir -p report
          echo "FilePath" > report/file_list.csv
          find Lesson_1 -type f >> report/file_list.csv

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: file-list-report
          path: report/file_list.csv
